
// Objective-C API for talking to the following Go packages
//
//	github.com/konglong147/securefile/experimental/libbox
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Foxboxvpn_FRAMEWORK_H__
#define __Foxboxvpn_FRAMEWORK_H__

#include "Foxboxvpn.objc.h"
#include "Universe.objc.h"

#endif
